//
// AllProducts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AllProducts: Codable, JSONEncodable, Hashable {

    public var products: [SingleProduct]?
    public var total: Double?
    public var skip: Double?
    public var limit: Double?

    public init(products: [SingleProduct]? = nil, total: Double? = nil, skip: Double? = nil, limit: Double? = nil) {
        self.products = products
        self.total = total
        self.skip = skip
        self.limit = limit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case products
        case total
        case skip
        case limit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(products, forKey: .products)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(skip, forKey: .skip)
        try container.encodeIfPresent(limit, forKey: .limit)
    }
}

